### ISSUE TITLE
Consider using cheerio for node.js usage

### ISSUE THREAD

**Issue by ben-eb** [augbog/twitter-card#2]
Instead of jQuery, you could use [cheerio](https://github.com/cheeriojs/cheerio) in node, which has a very jQuery-like API and the advantage of not having to be concerned about the DOM. It might be nice to use this module in node using cheerio, and the browser (via browserify) with `querySelector`. Just specify a different entry point for browserify in your `package.json`, e.g:

``` json
{
    "main": "index.js",
    "browser": "browser.js"
}
```

**Comment by augbog** [comment]
Oh very interesting. I will definitely look into it :) Thanks for submitting this as an issue. Also feel free to contribute!
